version: 1.0.{build}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

platform:
  - Any CPU

configuration:
  - Build

build:
  project: MemoryBus.sln

test:
  assemblies:
    - '**\*.tests.dll'

after_test:
  - ps: .\nuget\pack.ps1

artifacts:
  - path: '**\*.nupkg'

deploy:
  provider: NuGet
  api_key:
    secure: HaSaek5Q1Z81NJh/tlPJdtTLvOq4xCwCS9DtzXXWXiBVdjNr8sdCIR/8qLe+UB6+
  artifact: /.*\.nupkg/